public class ACETViewMemberListingResultsWrapper {
    public String firstName {get; set;}
    public String lastName {get; set;}
    public String memberID {get; set;}
    public String relationShip {get; set;}
    public String bundleId {get; set;}
    public String effectiveDate {get; set;}
    public String terminationDate {get; set;}
    public String contractType {get; set;}
    public String billingGroup {get; set;}
    public String status {get; set;}
    public String memberDOB {get; set;}

    public ACETViewMemberListingResultsWrapper() {
    
    }
}