public with sharing class ACETSystemUnavailableWrapper{
    
    public string actionRequested{get;set;}
    public string authorizedContact{get;set;}
    public string memberName{get;set;}
    public string SSNMemberId{get;set;}
    public string termDate{get;set;}
    public case tempCase{get;set;}
    public case tempCase2{get;set;}
    public case tempCase3{get;set;}
    public case tempCase4{get;set;}
    public case tempCase5{get;set;}
    public case tempCase6{get;set;}
    public string termReason{get;set;}
    public string selectedRouteTo{get;set;}
    public string homeAddress{get;set;}
    public string Phone{get;set;}
    public string dateOfBirth{get;set;}
    public string gender{get;set;}
    public string pcpGyne{get;set;}
    public date qualifyingEvent{get;set;}
    public string qualifyingReasonCode{get;set;}
    public date dateOfHire{get;set;}
    public string cspBg{get;set;}
    public date dateOfCoverage{get;set;}
    public string priorInfo{get;set;}
    public string coordinationOfBenefit{get;set;}
    public string enrollmentReason{get;set;}
    public string reinstatementReason{get;set;}
    public date reinstatementEffectiveDate{get;set;}
    public string coverageType {get; set;}
}