public class ACETVCCDInteractionInfo{
    
    public String callerType;
    public String idStr;
    //public String questionTypeCode;
    public String QuestionType;
    public String callerANI;
    public String TFN;
    public String MemberDOB;
    public String CallerID;
    public String TaxID;
    public String npi;
    public String MemberID;
    public String ClaimID;
    public String AuthorizationNumber;
    public String ReferralNumber;
}