public class ACETUpdIndividualMemResJSON2Apex{
	public cls_UpdateIndividualMembershipResponse UpdateIndividualMembershipResponse;
	class cls_UpdateIndividualMembershipResponse {
		public cls_response response;
	}
	class cls_response {
		public String responseCode;	//200
		public String responseDesc;	// STS0003-Record(s) updated. STS3021-All member benefit records associated to this bundle option are successfully updated. STS0003-Record(s) updated. STS3021-All member benefit records associated to this bundle option are successfully updated. STS0003-Record(s) updated.
	}
	
}