public class ACETHighlightsPanelAdditionalInfo {
    public String OriginatorRelationship {get;set;}
    public String Relationship {get;set;}    
    public String SitusState {get;set;}
    public String DOB {get;set;}
    public String EndDate {get;set;}
    public String BenefitPlanId {get;set;}    
    public String EffectiveDate {get;set;}
    public String PolicyNumber {get;set;}
    public String GroupName {get;set;}
    public String Product {get;set;}
    public String ProductType {get;set;}
    public String Network {get;set;}
    public String ConsumerAccountIndicator {get;set;}
    public String FirstName { get; set; }
    public String LastName { get; set; }
    public String Gender { get; set; }
    public String MemberId { get; set; }
    
    public String GroupNumber {get;set;}
    public String PhoneNumber {get;set;}
    public String EmployerName {get;set;}
    public String Zip {get;set;}
    public String State {get;set;}
    
    /*****Added By Sourabh******/
    public String UHCBS{get;set;}
    public String GroupN{get;set;}
    public String GroupStatus{get;set;}
    public String ServiceTeam{get;set;}
    public String EffectiveStartDate{get;set;}
    public String RiskManagement{get;set;}
    public String RatingMethod{get;set;}
    public String RenewalDate{get;set;}
    public String RelationshipType{get;set;}
    public String groupSName{get;set;}
    
    public string producerOriginator{get;set;}
    public string producerSubject{get;set;}
    public string producerId{get;set;}
    public string producerName{get;set;}
    
    public String providerType{get;set;}//added by Vishakha
    public String isMember{get;set;}//added by Vishakha
    public String isGroup{get;set;}//added by Vishakha
    
}