~
   "benefitAccumulatorRSRequest":~
	   "getBenefitsAccumulatorRequest":    ~
	      "benefitBundleOptionId":       "{0}",
	      "enrolleeIdentifier":       ~
	        "type": "{1}",
	         "id": "{2}"
	      },
	      "effectiveStartDate":       "{3}",
	      "effectiveEndDate":       "{4}",
	      "coverageTypes":       [~
	         "coverageType": "{5}"
	      }],
	      "benefitVersionIndicator":       "{6}",
	      "benefitCode":       "{7}"
	   }
	}
}