~
	"getMedicalHealthServiceCaseAuthorizationReq": ~
		"getAuthorizationRequestBaseType": ~
			"requestHeader": ~
				"srcSystem": "ACET",
				"logLevel": "DEBUG",
				"userID": ~
					"id": "{0}"
				}
			},
			"getAuthorizationRequest": [~
				"searchCriteria": ~
					"identifier": [~
						"sourceSysCode": "AUTHID",
						"id": {1}
					}, ~
						"sourceSysCode": "SRK",
						"id": {2}
					}]
				}
			}]
		}
	}
}